<?php

namespace Database\Seeders;

use App\Models\AutoDealer;
use Illuminate\Database\Seeder;

class AutoDealerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $autoDealers = [
            [
                'legal_business_name' => 'ABC Auto Dealership',
                'dba' => 'ABC Cars',
                'business_type' => 'LLC',
                'years_operation' => 5,
                'website_url' => 'https://abcautodealership.com',
                'contact_name' => 'John Smith',
                'contact_title' => 'General Manager',
                'contact_phone' => '(555) 123-4567',
                'contact_email' => 'john.smith@abcautodealership.com',
                'main_address' => '123 Main Street, Anytown, CA 90210',
                'multiple_locations' => 'yes',
                'additional_addresses' => '456 Oak Avenue, Somewhere, CA 90211',
                'dealer_license' => 'DL123456',
                'federal_tax_id' => '12-3456789',
                'duns_number' => '123456789',
                'cars_per_month' => 25,
                'vehicle_types' => ['new', 'used', 'luxury'],
                'transport_preference' => 'enclosed',
                'delivery_type' => 'door_to_door',
                'inventory_contact' => 'Jane Doe - (555) 987-6543',
                'pickup_times' => '9:00 AM - 5:00 PM',
                'delivery_days' => 'Monday - Friday',
                'billing_contact' => 'Mike Johnson',
                'billing_email' => 'billing@abcautodealership.com',
                'payment_method' => 'ach',
                'vendor_platforms' => 'DealerTrack, vAuto',
                'nda_required' => 'yes',
                'trade_reference' => 'yes',
                'w9_upload' => 'auto_dealers/w9/sample_w9.pdf',
                'insurance_certificate' => 'auto_dealers/insurance/sample_insurance.pdf',
                'status' => 'approved',
                'admin_notes' => 'Established dealer with good track record. Approved for Net 15 terms.',
            ],
            [
                'legal_business_name' => 'XYZ Motors Inc.',
                'dba' => null,
                'business_type' => 'Corporation',
                'years_operation' => 12,
                'website_url' => 'https://xyzmotors.com',
                'contact_name' => 'Sarah Wilson',
                'contact_title' => 'Operations Director',
                'contact_phone' => '(555) 234-5678',
                'contact_email' => 'sarah.wilson@xyzmotors.com',
                'main_address' => '789 Business Blvd, Commerce City, TX 75001',
                'multiple_locations' => 'no',
                'additional_addresses' => null,
                'dealer_license' => 'DL789012',
                'federal_tax_id' => '98-7654321',
                'duns_number' => '987654321',
                'cars_per_month' => 15,
                'vehicle_types' => ['used', 'oversized'],
                'transport_preference' => 'open',
                'delivery_type' => 'terminal_to_terminal',
                'inventory_contact' => null,
                'pickup_times' => '8:00 AM - 6:00 PM',
                'delivery_days' => 'Monday - Saturday',
                'billing_contact' => 'Robert Brown',
                'billing_email' => 'accounts@xyzmotors.com',
                'payment_method' => 'ach',
                'vendor_platforms' => null,
                'nda_required' => 'no',
                'trade_reference' => 'no',
                'w9_upload' => 'auto_dealers/w9/sample_w9_2.pdf',
                'insurance_certificate' => null,
                'status' => 'pending',
                'admin_notes' => 'New application under review. Need to verify dealer license.',
            ],
            [
                'legal_business_name' => 'Premium Auto Group',
                'dba' => 'Premium Cars',
                'business_type' => 'LLC',
                'years_operation' => 8,
                'website_url' => 'https://premiumautogroup.com',
                'contact_name' => 'David Lee',
                'contact_title' => 'Fleet Manager',
                'contact_phone' => '(555) 345-6789',
                'contact_email' => 'david.lee@premiumautogroup.com',
                'main_address' => '321 Luxury Lane, Beverly Hills, CA 90210',
                'multiple_locations' => 'yes',
                'additional_addresses' => '654 Rodeo Drive, Beverly Hills, CA 90210',
                'dealer_license' => 'DL456789',
                'federal_tax_id' => '45-6789012',
                'duns_number' => '456789012',
                'cars_per_month' => 40,
                'vehicle_types' => ['luxury', 'new'],
                'transport_preference' => 'enclosed',
                'delivery_type' => 'door_to_door',
                'inventory_contact' => 'Lisa Chen - (555) 456-7890',
                'pickup_times' => '10:00 AM - 4:00 PM',
                'delivery_days' => 'Tuesday - Saturday',
                'billing_contact' => 'Amanda White',
                'billing_email' => 'finance@premiumautogroup.com',
                'payment_method' => 'ach',
                'vendor_platforms' => 'CDK Global, Reynolds & Reynolds',
                'nda_required' => 'yes',
                'trade_reference' => 'yes',
                'w9_upload' => 'auto_dealers/w9/sample_w9_3.pdf',
                'insurance_certificate' => 'auto_dealers/insurance/sample_insurance_3.pdf',
                'status' => 'approved',
                'admin_notes' => 'High-end luxury dealer. Approved for Net 30 terms with monthly billing.',
            ],
            [
                'legal_business_name' => 'Budget Auto Sales',
                'dba' => 'Budget Cars',
                'business_type' => 'Sole Proprietorship',
                'years_operation' => 3,
                'website_url' => null,
                'contact_name' => 'Maria Garcia',
                'contact_title' => 'Owner',
                'contact_phone' => '(555) 567-8901',
                'contact_email' => 'maria@budgetautosales.com',
                'main_address' => '987 Budget Street, Economy Town, FL 33101',
                'multiple_locations' => 'no',
                'additional_addresses' => null,
                'dealer_license' => 'DL567890',
                'federal_tax_id' => '56-7890123',
                'duns_number' => null,
                'cars_per_month' => 8,
                'vehicle_types' => ['used', 'inoperable'],
                'transport_preference' => 'open',
                'delivery_type' => 'terminal_to_terminal',
                'inventory_contact' => null,
                'pickup_times' => '9:00 AM - 5:00 PM',
                'delivery_days' => 'Monday - Friday',
                'billing_contact' => 'Maria Garcia',
                'billing_email' => 'maria@budgetautosales.com',
                'payment_method' => 'credit_card',
                'vendor_platforms' => null,
                'nda_required' => 'no',
                'trade_reference' => 'no',
                'w9_upload' => 'auto_dealers/w9/sample_w9_4.pdf',
                'insurance_certificate' => null,
                'status' => 'rejected',
                'admin_notes' => 'Application rejected due to insufficient business history and credit concerns.',
            ],
            [
                'legal_business_name' => 'Mega Auto Corporation',
                'dba' => 'Mega Cars',
                'business_type' => 'Corporation',
                'years_operation' => 20,
                'website_url' => 'https://megaautocorp.com',
                'contact_name' => 'James Anderson',
                'contact_title' => 'VP of Operations',
                'contact_phone' => '(555) 678-9012',
                'contact_email' => 'james.anderson@megaautocorp.com',
                'main_address' => '555 Corporate Plaza, Business District, NY 10001',
                'multiple_locations' => 'yes',
                'additional_addresses' => '777 Enterprise Ave, Business District, NY 10001',
                'dealer_license' => 'DL678901',
                'federal_tax_id' => '67-8901234',
                'duns_number' => '678901234',
                'cars_per_month' => 75,
                'vehicle_types' => ['new', 'used', 'luxury', 'oversized'],
                'transport_preference' => 'enclosed',
                'delivery_type' => 'door_to_door',
                'inventory_contact' => 'Tom Wilson - (555) 789-0123',
                'pickup_times' => '7:00 AM - 7:00 PM',
                'delivery_days' => 'Monday - Sunday',
                'billing_contact' => 'Jennifer Davis',
                'billing_email' => 'ap@megaautocorp.com',
                'payment_method' => 'ach',
                'vendor_platforms' => 'ADP Dealer Services, DealerSocket',
                'nda_required' => 'yes',
                'trade_reference' => 'yes',
                'w9_upload' => 'auto_dealers/w9/sample_w9_5.pdf',
                'insurance_certificate' => 'auto_dealers/insurance/sample_insurance_5.pdf',
                'status' => 'approved',
                'admin_notes' => 'Major auto group with excellent credit. Approved for Net 30 with enterprise terms.',
            ],
        ];

        foreach ($autoDealers as $autoDealer) {
            AutoDealer::create($autoDealer);
        }
    }
}
