<?php

namespace Database\Seeders;

use App\Models\CorporateGovernmentFleet;
use Illuminate\Database\Seeder;

class CorporateGovernmentFleetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fleets = [
            [
                'legal_organization_name' => 'City of Atlanta Fleet Management',
                'dba' => 'Atlanta Fleet Services',
                'business_type' => 'government',
                'department' => 'Fleet Management',
                'years_operation' => 15,
                'website_url' => 'https://www.atlantaga.gov/fleet',
                'contact_name' => 'Michael Johnson',
                'contact_title' => 'Fleet Manager',
                'contact_phone' => '(404) 555-0123',
                'contact_email' => 'michael.johnson@atlantaga.gov',
                'fulfillment_address' => '1234 Peachtree Street, Atlanta, GA 30309',
                'fleet_locations' => 8,
                'vehicle_release_contact' => 'Sarah Williams',
                'fleet_management_software' => 'Fleetio',
                'usage_type' => ['law_enforcement', 'utility', 'passenger'],
                'vehicle_condition' => 'mixed',
                'vehicles_per_month' => 25,
                'transport_type' => 'open',
                'transport_scope' => 'regional',
                'security_requirements' => 'GPS tracking required',
                'pickup_protocols' => '24-hour notice required. Vehicles must be picked up during business hours (8 AM - 5 PM).',
                'special_handling' => 'Some vehicles require special equipment for transport.',
                'billing_contact' => 'Jennifer Davis',
                'billing_email' => 'billing@atlantaga.gov',
                'payment_method' => 'government_po',
                'vendor_portal_invoicing' => 'yes',
                'payment_platform' => 'City of Atlanta Vendor Portal',
                'government_corporate_id' => 'storage/sample_documents/atlanta_gov_id.pdf',
                'w9_upload' => 'storage/sample_documents/atlanta_w9.pdf',
                'insurance_certificate' => 'storage/sample_documents/atlanta_insurance.pdf',
                'purchase_order_format' => 'storage/sample_documents/atlanta_po_format.pdf',
                'references_contractors' => 'ABC Transport Services, XYZ Logistics',
                'status' => 'approved',
                'admin_notes' => 'Approved for regional transport services. Good payment history.',
            ],
            [
                'legal_organization_name' => 'FedEx Corporation',
                'dba' => 'FedEx Fleet Operations',
                'business_type' => 'corporate',
                'department' => 'Fleet Operations',
                'years_operation' => 25,
                'website_url' => 'https://www.fedex.com',
                'contact_name' => 'David Rodriguez',
                'contact_title' => 'Senior Fleet Director',
                'contact_phone' => '(901) 555-0456',
                'contact_email' => 'david.rodriguez@fedex.com',
                'fulfillment_address' => '942 South Shady Grove Road, Memphis, TN 38120',
                'fleet_locations' => 45,
                'vehicle_release_contact' => 'Lisa Thompson',
                'fleet_management_software' => 'Samsara',
                'usage_type' => ['passenger', 'utility'],
                'vehicle_condition' => 'mostly_new',
                'vehicles_per_month' => 150,
                'transport_type' => 'enclosed',
                'transport_scope' => 'nationwide',
                'security_requirements' => 'High security clearance required',
                'pickup_protocols' => '48-hour advance notice. Security clearance verification required. Vehicles must be transported in enclosed carriers.',
                'special_handling' => 'All vehicles require enclosed transport. Temperature-controlled environment preferred.',
                'billing_contact' => 'Robert Chen',
                'billing_email' => 'fleet.billing@fedex.com',
                'payment_method' => 'ach',
                'vendor_portal_invoicing' => 'yes',
                'payment_platform' => 'FedEx Vendor Portal',
                'government_corporate_id' => 'storage/sample_documents/fedex_corp_id.pdf',
                'w9_upload' => 'storage/sample_documents/fedex_w9.pdf',
                'insurance_certificate' => 'storage/sample_documents/fedex_insurance.pdf',
                'purchase_order_format' => null,
                'references_contractors' => 'National Transport Solutions, Global Logistics Inc.',
                'status' => 'approved',
                'admin_notes' => 'Premium corporate client. Excellent payment terms. Priority handling required.',
            ],
            [
                'legal_organization_name' => 'State of California Department of Transportation',
                'dba' => 'Caltrans Fleet',
                'business_type' => 'government',
                'department' => 'Fleet Management Division',
                'years_operation' => 30,
                'website_url' => 'https://dot.ca.gov',
                'contact_name' => 'Patricia Martinez',
                'contact_title' => 'Fleet Administrator',
                'contact_phone' => '(916) 555-0789',
                'contact_email' => 'patricia.martinez@dot.ca.gov',
                'fulfillment_address' => '1120 N Street, Sacramento, CA 95814',
                'fleet_locations' => 12,
                'vehicle_release_contact' => 'James Wilson',
                'fleet_management_software' => 'Geotab',
                'usage_type' => ['utility', 'construction'],
                'vehicle_condition' => 'mostly_used',
                'vehicles_per_month' => 40,
                'transport_type' => 'open',
                'transport_scope' => 'local',
                'security_requirements' => 'Standard government security protocols',
                'pickup_protocols' => '72-hour notice required. Vehicles must be picked up during business hours. Government ID required.',
                'special_handling' => 'Some construction vehicles require special permits for transport.',
                'billing_contact' => 'Maria Garcia',
                'billing_email' => 'fleet.billing@dot.ca.gov',
                'payment_method' => 'government_po',
                'vendor_portal_invoicing' => 'yes',
                'payment_platform' => 'Caltrans Vendor Portal',
                'government_corporate_id' => 'storage/sample_documents/caltrans_gov_id.pdf',
                'w9_upload' => 'storage/sample_documents/caltrans_w9.pdf',
                'insurance_certificate' => 'storage/sample_documents/caltrans_insurance.pdf',
                'purchase_order_format' => 'storage/sample_documents/caltrans_po_format.pdf',
                'references_contractors' => 'California Transport Services, Pacific Fleet Solutions',
                'status' => 'pending',
                'admin_notes' => 'Pending review of government credentials and insurance documentation.',
            ],
            [
                'legal_organization_name' => 'Amazon.com Services LLC',
                'dba' => 'Amazon Fleet Operations',
                'business_type' => 'corporate',
                'department' => 'Last Mile Fleet',
                'years_operation' => 8,
                'website_url' => 'https://www.amazon.com',
                'contact_name' => 'Christopher Lee',
                'contact_title' => 'Fleet Operations Manager',
                'contact_phone' => '(206) 555-0321',
                'contact_email' => 'christopher.lee@amazon.com',
                'fulfillment_address' => '410 Terry Avenue North, Seattle, WA 98109',
                'fleet_locations' => 35,
                'vehicle_release_contact' => 'Amanda Foster',
                'fleet_management_software' => 'Fleetio',
                'usage_type' => ['passenger', 'utility'],
                'vehicle_condition' => 'mostly_new',
                'vehicles_per_month' => 200,
                'transport_type' => 'enclosed',
                'transport_scope' => 'nationwide',
                'security_requirements' => 'High security clearance. NDA required.',
                'pickup_protocols' => '24-hour notice. Security clearance verification. NDA must be signed. Enclosed transport only.',
                'special_handling' => 'All vehicles require enclosed transport. Temperature and humidity controlled environment.',
                'billing_contact' => 'Kevin Brown',
                'billing_email' => 'fleet.accounts@amazon.com',
                'payment_method' => 'net_terms',
                'vendor_portal_invoicing' => 'yes',
                'payment_platform' => 'Amazon Vendor Portal',
                'government_corporate_id' => 'storage/sample_documents/amazon_corp_id.pdf',
                'w9_upload' => 'storage/sample_documents/amazon_w9.pdf',
                'insurance_certificate' => 'storage/sample_documents/amazon_insurance.pdf',
                'purchase_order_format' => null,
                'references_contractors' => 'Prime Transport Solutions, Amazon Logistics Partners',
                'status' => 'approved',
                'admin_notes' => 'Premium enterprise client. Net 30 payment terms. Priority handling required.',
            ],
            [
                'legal_organization_name' => 'United Parcel Service of America',
                'dba' => 'UPS Fleet Management',
                'business_type' => 'corporate',
                'department' => 'Fleet Services',
                'years_operation' => 20,
                'website_url' => 'https://www.ups.com',
                'contact_name' => 'Jennifer Taylor',
                'contact_title' => 'Fleet Director',
                'contact_phone' => '(404) 555-0987',
                'contact_email' => 'jennifer.taylor@ups.com',
                'fulfillment_address' => '55 Glenlake Parkway NE, Atlanta, GA 30328',
                'fleet_locations' => 28,
                'vehicle_release_contact' => 'Mark Anderson',
                'fleet_management_software' => 'Samsara',
                'usage_type' => ['passenger', 'utility'],
                'vehicle_condition' => 'mixed',
                'vehicles_per_month' => 120,
                'transport_type' => 'enclosed',
                'transport_scope' => 'regional',
                'security_requirements' => 'Standard corporate security protocols',
                'pickup_protocols' => '48-hour notice required. Corporate ID verification. Enclosed transport preferred.',
                'special_handling' => 'Some vehicles require special equipment for loading/unloading.',
                'billing_contact' => 'Rachel Green',
                'billing_email' => 'fleet.billing@ups.com',
                'payment_method' => 'ach',
                'vendor_portal_invoicing' => 'yes',
                'payment_platform' => 'UPS Vendor Portal',
                'government_corporate_id' => 'storage/sample_documents/ups_corp_id.pdf',
                'w9_upload' => 'storage/sample_documents/ups_w9.pdf',
                'insurance_certificate' => 'storage/sample_documents/ups_insurance.pdf',
                'purchase_order_format' => null,
                'references_contractors' => 'UPS Approved Carriers, National Fleet Solutions',
                'status' => 'approved',
                'admin_notes' => 'Established corporate client. Reliable payment history. Good communication.',
            ],
        ];

        foreach ($fleets as $fleet) {
            CorporateGovernmentFleet::create($fleet);
        }
    }
}
